# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculadora.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def __init__(self):
        self.__valor = ''
        self.__valorMemoria = 0
        self.__operacao = ''
        # self.__operandoB = 0

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Calculadora")
        MainWindow.resize(386, 432)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.btn_7 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_7.setGeometry(QtCore.QRect(40, 90, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_7.setFont(font)
        self.btn_7.setObjectName("btn_7")
        self.btn_7.clicked.connect(self.botao7)

        self.btn_8 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_8.setGeometry(QtCore.QRect(120, 90, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_8.setFont(font)
        self.btn_8.setObjectName("btn_8")
        self.btn_8.clicked.connect(self.botao8)

        self.btn_9 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_9.setGeometry(QtCore.QRect(200, 90, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_9.setFont(font)
        self.btn_9.setObjectName("btn_9")
        self.btn_9.clicked.connect(self.botao9)

        self.btn_4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_4.setGeometry(QtCore.QRect(40, 160, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_4.setFont(font)
        self.btn_4.setObjectName("btn_4")
        self.btn_4.clicked.connect(self.botao4)

        self.btn_5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_5.setGeometry(QtCore.QRect(120, 160, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_5.setFont(font)
        self.btn_5.setObjectName("btn_5")
        self.btn_5.clicked.connect(self.botao5)

        self.btn_6 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_6.setGeometry(QtCore.QRect(200, 160, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_6.setFont(font)
        self.btn_6.setObjectName("btn_6")
        self.btn_6.clicked.connect(self.botao6)

        self.btn_1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_1.setGeometry(QtCore.QRect(40, 230, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_1.setFont(font)
        self.btn_1.setObjectName("btn_1")
        self.btn_1.clicked.connect(self.botao1)

        self.btn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_2.setGeometry(QtCore.QRect(120, 230, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_2.setFont(font)
        self.btn_2.setObjectName("btn_2")
        self.btn_2.clicked.connect(self.botao2)

        self.btn_3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_3.setGeometry(QtCore.QRect(200, 230, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_3.setFont(font)
        self.btn_3.setObjectName("btn_3")
        self.btn_3.clicked.connect(self.botao3)

        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(40, 20, 311, 61))
        self.lcdNumber.setDigitCount(10)
        self.lcdNumber.setObjectName("lcdNumber")

        self.btn_0 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_0.setGeometry(QtCore.QRect(40, 300, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_0.setFont(font)
        self.btn_0.setObjectName("btn_0")
        self.btn_0.clicked.connect(self.botao0)

        self.btn_igual = QtWidgets.QPushButton(self.centralwidget)
        self.btn_igual.setGeometry(QtCore.QRect(120, 300, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_igual.setFont(font)
        self.btn_igual.setObjectName("btn_igual")
        self.btn_igual.clicked.connect(self.botaoIgual)

        self.btn_divisao = QtWidgets.QPushButton(self.centralwidget)
        self.btn_divisao.setGeometry(QtCore.QRect(280, 160, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_divisao.setFont(font)
        self.btn_divisao.setObjectName("btn_divisao")
        self.btn_divisao.clicked.connect(self.botaoDivisao)

        self.btn_multiplicacao = QtWidgets.QPushButton(self.centralwidget)
        self.btn_multiplicacao.setGeometry(QtCore.QRect(280, 230, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_multiplicacao.setFont(font)
        self.btn_multiplicacao.setObjectName("btn_multiplicacao")
        self.btn_multiplicacao.clicked.connect(self.botaoMultiplicacao)

        self.btn_subtracao = QtWidgets.QPushButton(self.centralwidget)
        self.btn_subtracao.setGeometry(QtCore.QRect(280, 300, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_subtracao.setFont(font)
        self.btn_subtracao.setObjectName("btn_subtracao")
        self.btn_subtracao.clicked.connect(self.botaoSubtracao)

        self.btn_adicao = QtWidgets.QPushButton(self.centralwidget)
        self.btn_adicao.setGeometry(QtCore.QRect(200, 300, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_adicao.setFont(font)
        self.btn_adicao.setObjectName("btn_adicao")
        self.btn_adicao.clicked.connect(self.botaoAdicao)

        self.btn_clean = QtWidgets.QPushButton(self.centralwidget)
        self.btn_clean.setGeometry(QtCore.QRect(280, 90, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_clean.setFont(font)
        self.btn_clean.setObjectName("btn_clean")
        self.btn_clean.clicked.connect(self.botaoClean)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 386, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculadora"))
        self.btn_7.setText(_translate("MainWindow", "7"))
        self.btn_8.setText(_translate("MainWindow", "8"))
        self.btn_9.setText(_translate("MainWindow", "9"))
        self.btn_4.setText(_translate("MainWindow", "4"))
        self.btn_5.setText(_translate("MainWindow", "5"))
        self.btn_6.setText(_translate("MainWindow", "6"))
        self.btn_1.setText(_translate("MainWindow", "1"))
        self.btn_2.setText(_translate("MainWindow", "2"))
        self.btn_3.setText(_translate("MainWindow", "3"))
        self.btn_0.setText(_translate("MainWindow", "0"))
        self.btn_igual.setText(_translate("MainWindow", "="))
        self.btn_divisao.setText(_translate("MainWindow", "/"))
        self.btn_multiplicacao.setText(_translate("MainWindow", "*"))
        self.btn_subtracao.setText(_translate("MainWindow", "-"))
        self.btn_adicao.setText(_translate("MainWindow", "+"))
        self.btn_clean.setText(_translate("MainWindow", "C"))

    def botao0(self):
        self.__valor = self.__valor + "0"
        self.lcdNumber.display((int(self.__valor)))

    def botao1(self):
        self.__valor = self.__valor + "1"
        self.lcdNumber.display((int(self.__valor)))

    def botao2(self):
        self.__valor = self.__valor + "2"
        self.lcdNumber.display((int(self.__valor)))

    def botao3(self):
        self.__valor = self.__valor + "3"
        self.lcdNumber.display((int(self.__valor)))

    def botao4(self):
        self.__valor = self.__valor + "4"
        self.lcdNumber.display((int(self.__valor)))

    def botao5(self):
        self.__valor = self.__valor + "5"
        self.lcdNumber.display((int(self.__valor)))

    def botao6(self):
        self.__valor = self.__valor + "6"
        self.lcdNumber.display((int(self.__valor)))

    def botao7(self):
        self.__valor = self.__valor+"7"
        self.lcdNumber.display((int(self.__valor)))

    def botao8(self):
        self.__valor = self.__valor + "8"
        self.lcdNumber.display((int(self.__valor)))

    def botao9(self):
        self.__valor = self.__valor + "9"
        self.lcdNumber.display((int(self.__valor)))

    def botaoClean(self):
        self.__valor = "0"
        self.lcdNumber.display((int(self.__valor)))

    def botaoAdicao(self):
        self.__valorMemoria = self.__valor
        self.__operacao = "+"
        self.botaoClean()

    def botaoSubtracao(self):
        self.__valorMemoria = self.lcdNumber.value()
        self.__operacao = "-"
        self.botaoClean()

    def botaoMultiplicacao(self):
        self.__valorMemoria = self.lcdNumber.value()
        self.__operacao = "*"
        self.botaoClean()

    def botaoDivisao(self):
        self.__valorMemoria = self.lcdNumber.value()
        self.__operacao = "/"
        self.botaoClean()

    def botaoIgual(self):
        # self.__operandoB = self.lcdNumber.value()
        if self.__operacao == "+":
            resultado = int(self.__valorMemoria) + self.lcdNumber.value()
        if self.__operacao == "-":
            resultado = int(self.__valorMemoria) - self.lcdNumber.value()
        if self.__operacao == "*":
            resultado = int(self.__valorMemoria) * self.lcdNumber.value()
        if self.__operacao == "/":
            if self.lcdNumber.value() == 0:
                resultado = 0
            resultado = int(self.__valorMemoria) / self.lcdNumber.value()
        self.lcdNumber.display(resultado)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
