# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telaCliente.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(614, 339)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.btnIncluir = QtWidgets.QPushButton(self.centralwidget)
        self.btnIncluir.setGeometry(QtCore.QRect(450, 50, 141, 41))
        self.btnIncluir.setObjectName("btnIncluir")

        # self.btnIncluir.clicked.connect(self._on_incluir_clicked)

        self.btnExcluir = QtWidgets.QPushButton(self.centralwidget)
        self.btnExcluir.setGeometry(QtCore.QRect(450, 100, 141, 41))
        self.btnExcluir.setObjectName("btnExcluir")


        self.btnAlterar = QtWidgets.QPushButton(self.centralwidget)
        self.btnAlterar.setGeometry(QtCore.QRect(450, 150, 141, 41))
        self.btnAlterar.setObjectName("btnAlterar")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(230, 250, 141, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 30, 211, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 211, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 170, 211, 16))
        self.label_3.setObjectName("label_3")
        self.txtNome = QtWidgets.QLineEdit(self.centralwidget)
        self.txtNome.setGeometry(QtCore.QRect(20, 50, 381, 20))
        self.txtNome.setObjectName("txtNome")

        self.txtEndereco = QtWidgets.QLineEdit(self.centralwidget)
        self.txtEndereco.setGeometry(QtCore.QRect(20, 120, 381, 20))
        self.txtEndereco.setObjectName("txtEndereco")

        self.txtCidade = QtWidgets.QLineEdit(self.centralwidget)
        self.txtCidade.setGeometry(QtCore.QRect(20, 190, 381, 20))
        self.txtCidade.setObjectName("txtCidade")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 614, 21))
        self.menubar.setObjectName("menubar")

        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionincluirAluno = QtWidgets.QAction(MainWindow)
        self.actionincluirAluno.setObjectName("actionincluirAluno")
        self.actionExcluirAluno = QtWidgets.QAction(MainWindow)
        self.actionExcluirAluno.setObjectName("actionExcluirAluno")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnIncluir.setText(_translate("MainWindow", "Incluir Cliente"))
        self.btnExcluir.setText(_translate("MainWindow", "Excluir"))
        self.btnAlterar.setText(_translate("MainWindow", "Alterar"))
        self.pushButton_4.setText(_translate("MainWindow", "Finalizar"))
        self.label.setText(_translate("MainWindow", "Informe o nome completo"))
        self.label_2.setText(_translate("MainWindow", "Informe o endereço"))
        self.label_3.setText(_translate("MainWindow", "Informe a Cidade"))
        self.actionincluirAluno.setText(_translate("MainWindow", "incluirAluno"))
        self.actionExcluirAluno.setText(_translate("MainWindow", "ExcluirAluno"))

"""
    def _on_incluir_clicked(self):
        aluno = Aluno()
        aluno.nome = self.txtNome.text()
        aluno.endereco = self.txtEndereco.text()
        aluno.cidade = self.txtCidade.text()

        print(aluno.nome)
        daoaluno.incluirAluno(aluno)


    def _on_alterar_clicked(self):
        print('oi')

"""


import sys
sys.path.insert(0,'../modelo')
sys.path.insert(1,'../controle')
from aluno import *
# from controleAluno import *
# from janela import *
# daoaluno = ControleAluno()

app = QtWidgets.QApplication(sys.argv)
MainsWindow = QtWidgets.QMainWindow()
ui = Ui_MainWindow()
ui.setupUi(MainsWindow)
MainsWindow.show()
sys.exit(app.exec_())